Compile items after Import All
intersystems/git-source-control pull request #368
Opened 2024-06-20 16:00 UTC by isc-pbarton

Fixes #362

2024-06-20 21:33 UTC, raymond-rebbeck commented
Please make this configurable. The codebase I work with requires some classes to be compiled in a particular order on first import for reasons that are not practical to address in the short term. I am concerned that this will cause problems for us.

2024-06-21 09:53 UTC, isc-tleavitt commented
@isc-pbarton the point @raymond-rebbeck raises is fair - let's make this configurable, but we want to default to compiling (particularly for the sake of less-technical interop users who wouldn't necessarily understand the implications).

2024-06-21 09:58 UTC, isc-tleavitt requested changes
Two points here: configurability is needed (defaulting to compile but should be able to turn it off), and we should compile everything after loading everything rather than compiling each thing as it's loaded.

2024-06-21 09:58 UTC, isc-tleavitt commented on cls/SourceControl/Git/Utils.cls
> -                set sc = $system.OBJ.Load(filename,"-l-d")
Interesting that we were using -l - I wonder if there was a reason for this. I agree that displaying output is reasonable, for sure.

Question - what's the behavior if a single item fails to load/compile?

A better architecture here would be to maintain a list of things that were loaded by specific calls to ImportItem and then compile all of them at the same time after all have been loaded. As written this is likely to hit dependencies (especially on initial load); with compilation at the end it at least *should* be possible for a developer to fix compilation dependencies with the right values for System, CompileAfter, DependsOn, etc.

2024-06-24 15:13 UTC, isc-tleavitt commented on cls/SourceControl/Git/Utils.cls
> -                set sc = $system.OBJ.Load(filename,"-l-d")
Note from discussion today: just use PullEventHandler

2024-06-27 14:04 UTC, isc-tleavitt approved these changes
Looks good

2024-06-27 14:04 UTC, merged