Merge and Rebase now don't use diff to synchronize file system with IRIS
intersystems/git-source-control pull request #384
Opened 2024-06-26 16:01 UTC by isc-hwojnick

Merge and Rebase use the output of the command itself to drive their synchronization with IRIS. 

ex:
the merge command will output:
> Merge made by the 'ort' strategy. 
> cls/package/newb4.cls | 5 ----- 
> cls/package/newb5.cls | 5 ----- 
> cls/package/newb7.cls | 5 +++++ 
> 3 files changed, 5 insertions(+), 10 deletions(-)
> delete mode 100644 cls/package/newb4.cls 
> delete mode 100644 cls/package/newb5.cls 
> create mode 100644 cls/package/newb7.cls 

The last 3 lines of the output are used to sync iris with the filesystem

2024-06-26 17:53 UTC, isc-pbarton requested changes
Merge and checkout of local and remote branches are working great for me.
Pull is having the issue from before where deletes/adds on the local branch get undone - but that is preexisting behavior for as long as the pull function was added. We could create a new issue to address that later by using the same logic as merge and checkout.
The preview pull on pull.csp is broken again and doesn't display any output. That should be fixed, I think by printing the output streams after preview in %zpkg.isc.sc.git.Socket

2024-06-26 18:18 UTC, isc-hwojnick commented
As for the previewing, I think I can fix that

2024-06-26 19:02 UTC, isc-pbarton approved these changes

2024-06-27 14:03 UTC, isc-tleavitt approved these changes

2024-06-27 14:03 UTC, merged