Instance wide uncommitted queue
intersystems/git-source-control pull request #436
Opened 2024-07-23 13:55 UTC by isc-hwojnick

Fixes #370

2024-08-06 18:04 UTC, isc-tleavitt requested changes
One really tiny nitpick, otherwise good.

2024-08-06 18:04 UTC, isc-tleavitt commented on cls/SourceControl/Git/Utils.cls
> +
Nit: remove extra whitespace (blank lines)

2024-08-06 18:21 UTC, isc-tleavitt requested changes
One tiny nit, and a request: please test this as a user with just %Developer to make sure it all works properly without doing extra SQL security work.

2024-08-06 18:21 UTC, isc-tleavitt commented
Can retarget this to main at this point.

2024-08-21 15:52 UTC, isc-pbarton commented
I made some fixes to get this working with %Developer roles, and a couple other minor improvements:

- The alert will no longer show up if I have the item edited in the current namespace
- There's now a setting in Configure I can use to turn off the alerts entirely

2024-08-26 15:11 UTC, isc-tleavitt requested changes
Two nitpicks and one SQL security question.

2024-08-26 15:11 UTC, isc-tleavitt commented on cls/SourceControl/Git/Change.cls
> +        while resultSet.%Next() {
Should check byref %Status from %Next(.sc) in/after loop

2024-08-26 15:11 UTC, isc-tleavitt commented on cls/SourceControl/Git/Utils.cls
> +    while resultSet.%Next() {
Should check byref %Status from %Next(.sc) inside/outside of loop

2024-08-26 15:11 UTC, isc-tleavitt commented on cls/SourceControl/Git/Utils.cls
> +    set resultSet = ##class(SourceControl.Git.Change).InstanceUncommittedFunc()
Concern: is this going to hit SQL privilege issues?

2024-09-26 16:46 UTC, isc-tleavitt requested changes
Just a bit of housekeeping in CHANGELOG.md and module.xml needed here, then good to go.

2024-09-27 13:58 UTC, isc-tleavitt approved these changes

2024-09-27 13:58 UTC, merged