Sync webui
intersystems/git-source-control pull request #441
Opened 2024-07-29 19:20 UTC by isc-hwojnick

Fixes #415 

New simple UI flow for the Sync operation

2024-07-30 18:00 UTC, isc-pbarton requested changes

2024-07-30 18:00 UTC, isc-pbarton commented on cls/SourceControl/Git/Utils.cls
> +        #; if ..CheckForUncommittedFiles() {
Let's delete these commented lines

2024-07-30 18:00 UTC, isc-pbarton commented on csp/sync.csp
> +                                    &html<<li class="list-group-item #(action)#">#(file)#</li>>
Just out of principle let's add protection against cross-site scripting wherever we inject data into the HTML.
```suggestion
                                    &html<<li class="list-group-item #(..EscapeHTML(action))#">#(file)#</li>>
```

2024-07-30 18:00 UTC, isc-pbarton commented on csp/sync.csp
> +                        <input class="form-control" type="text" name="syncMsg" id="syncMsg" value="#(commitMsg)#">
Same as before - add EscapeHTML

2024-07-30 18:00 UTC, isc-pbarton commented on csp/sync.csp
> +    function disableInput() {
Let's rename this function if we're going to have it actually perform the sync action

2024-07-30 18:00 UTC, isc-pbarton commented on csp/sync.csp
> +        set $NAMESPACE = "USER"
I don't think we want USER hardcoded as the namespace here

2024-07-30 20:27 UTC, isc-pbarton requested changes

2024-07-30 20:27 UTC, isc-pbarton commented on csp/sync.csp
> +                            &html<<p>Local changes will be merged with #(settings.defaultMergeBranch)# after receiving the latest changes</p>>
```suggestion
                            &html<<p>Local changes will be merged with #(..EscapeHTML(settings.defaultMergeBranch))# after receiving the latest changes</p>>
```

2024-07-30 20:27 UTC, isc-pbarton commented on csp/sync.csp
> +    function disableInput() {
Still pending

2024-07-30 20:27 UTC, isc-pbarton commented on csp/sync.csp
> +        set $NAMESPACE = "USER"
Still pending

2024-07-30 20:30 UTC, isc-hwojnick commented
@isc-pbarton I kept the name of the function to disable the input and moved the call to the hyperevent back to the onClick so no rename is needed

2024-08-06 18:22 UTC, isc-tleavitt commented on csp/sync.csp
> +		set %session.UseSessionCookie = 1 // Always set back to autodetect
It would be worth refactoring this to a shared method somewhere since many places use it. Doesn't need to happen in this PR though.

2024-08-06 18:22 UTC, isc-tleavitt approved these changes

2024-08-06 18:23 UTC, isc-tleavitt commented
Can retarget to main.

2024-08-07 13:40 UTC, merged