Change context webui
intersystems/git-source-control pull request #456
Opened 2024-08-05 13:36 UTC by isc-hwojnick

Fixes #280

2024-08-06 18:25 UTC, isc-tleavitt requested changes
A few small points, and please test as a user with just %Developer.

2024-08-06 18:25 UTC, isc-tleavitt commented on CHANGELOG.md
> +- New way to change context of Git-Source-Control from UI (#280)
Let's say "Allow changing namespaces and IPM package context from web UI"

2024-08-06 18:25 UTC, isc-tleavitt commented on cls/SourceControl/Git/WebUIDriver.cls
> +            set responseJSON = $NAMESPACE
Should be actual JSON for consistency

2024-08-06 18:25 UTC, isc-tleavitt commented on cls/SourceControl/Git/WebUIDriver.cls
> +            set responseJSON = $NAMESPACE
Actually, this seems unused (we just use the URL in the client code) - should just remove.

2024-08-16 11:24 UTC, isc-tleavitt commented
@isc-hwojnick to confirm, did you test this as %Developer?

2024-08-16 14:06 UTC, isc-hwojnick commented
I was waiting on the %Dev global fix before doing thorough %Develop testing

2024-08-23 19:13 UTC, isc-tleavitt approved these changes

2024-08-23 19:13 UTC, merged