Allow editing of files via web application
intersystems/git-source-control pull request #466
Opened 2024-08-29 13:56 UTC by isc-tleavitt

Fixes #464 

Also adds a VSCode workspace download link to the Git WebUI.

2024-08-30 13:04 UTC, isc-tleavitt reviewed
Need to also fix #453 to avoid serious issues in a HCC setting where this will be used.

2024-08-30 13:04 UTC, isc-tleavitt commented on cls/SourceControl/Git/WebUIDriver.cls
> +                {
From discussion yesterday: should only add this folder if 'hasCSP

2024-09-05 16:01 UTC, isc-pbarton requested changes

2024-09-12 17:57 UTC, isc-tleavitt commented on git-webui/src/share/git-webui/webui/css/git-webui.less
> +            bottom: 40px;
Good old IE box model... thanks, great catch!

2024-09-12 19:50 UTC, isc-pbarton approved these changes

2024-09-12 20:39 UTC, merged