Add description of HCC workflow
intersystems/git-source-control pull request #543
Opened 2024-10-15 17:49 UTC by isc-etamarch

Addresses #32

2024-10-15 17:50 UTC, isc-etamarch commented
@isc-tleavitt Not sure if I got the merge request part of the HCC workflow correct.

2024-10-15 22:44 UTC, isc-tleavitt requested changes
A few initial points of feedback - this is all accurate for more of an expert mode / Git WebUI-based workflow, but not actually the starting point for the Health Connect Cloud workflow.

2024-10-15 22:44 UTC, isc-tleavitt commented on docs/hcc.md
> +### Feature branches
We came up with the term "Interface branch" in a different discussion you may or may not have been part of; let's use that.

2024-10-15 22:44 UTC, isc-tleavitt commented on docs/hcc.md
> +After this, you can start working on the change.
This is more of an expert mode workflow, really. I'm realizing that you might not have actually had enough context on basic mode to talk through the workflow. None of this is wrong, it's just too complicated for what we want to start with for someone with zero git background.

I'd honestly be fine with repurposing all you have as the expert mode documentation / as part of the coverage of Git WebUI. This is largely useful content still, just not for the bare-bones simplest-possible Health Connect Cloud use case.

2024-10-16 16:23 UTC, isc-tleavitt approved these changes
Just going to merge these because they're an incremental improvement; we can keep iterating.

2024-10-16 16:24 UTC, merged