Initialize uses entered repo
intersystems/git-source-control pull request #571
Opened 2024-10-23 20:43 UTC by isc-etamarch

Fixes #486

2024-10-23 20:56 UTC, isc-tleavitt requested changes
Just a really dumb nitpick here, sorry

2024-10-23 20:56 UTC, isc-tleavitt commented on cls/_zpkg/isc/sc/git/Socket.cls
> +            }
Spacing here is generally funky

2024-10-23 20:56 UTC, isc-tleavitt commented on csp/gitprojectsettings.csp
> +    var root = document.getElementById("namespaceTemp").value;
Here too

2024-10-23 21:01 UTC, isc-etamarch commented
Weird, had to delete and re-type the spaces since they looked fine in my editor lol

2024-10-24 13:44 UTC, isc-tleavitt reviewed
One more point I missed the first time around.

2024-10-24 13:44 UTC, isc-tleavitt commented on cls/_zpkg/isc/sc/git/Socket.cls
> +		if (root '= "") && ($extract(root,1,3) '= "e.g") {
Wait - why do we need to check for e.g? This is the placeholder, not the value; we wouldn't ever send that?

2024-10-24 14:34 UTC, isc-tleavitt approved these changes

2024-10-24 14:35 UTC, merged