Fix diffview
intersystems/git-source-control pull request #608
Opened 2024-10-30 15:21 UTC by isc-etamarch

Fixes #590

2024-10-30 16:58 UTC, isc-tleavitt requested changes

2024-10-30 16:58 UTC, isc-tleavitt commented on git-webui/release/share/git-webui/webui/js/git-webui.js
> +        self.update(...[,,,,],1);
This is definitely going to break in Studio

2024-10-30 16:58 UTC, isc-tleavitt commented on git-webui/src/share/git-webui/webui/js/git-webui.js
> +    self.update = function(cmd, diffOpts, file, mode, reRun) {
Cleaner approach: write a function that does everything after setting the 4 options, and call that instead of calling update with reRun set to true?

2024-10-30 20:08 UTC, isc-tleavitt requested changes
You need to re-run `zpm "git-source-control activate"` to get changes moved to release. (And then test, because if they're not in release you haven't tried them yet!)

2024-10-30 20:47 UTC, isc-etamarch commented
@isc-tleavitt should be all set now

2024-10-31 11:42 UTC, isc-tleavitt approved these changes

2024-10-31 11:42 UTC, merged