HCC docs work in progress
intersystems/git-source-control pull request #635
Opened 2024-11-08 21:47 UTC by isc-pbarton

Updates to Health Connect Cloud documentation.

2024-11-12 17:36 UTC, isc-tleavitt requested changes
a few really minor points here. I've also passed along to DP PM to review but that review shouldn't hold it up, we can go with a followup if needed

2024-11-12 17:36 UTC, isc-tleavitt commented on docs/hcc.md
> +The recommended workflow for Health Connect Cloud is to: create an interface branch, make changes, sync them to GitLab, create a merge request, review and approve the merge request, and then pull the
Nit: "pull the changes" sounds like an action but is automatic with CI/CD.

2024-11-12 17:36 UTC, isc-tleavitt commented on docs/hcc.md
> +   - [Official Change Control Documentation](https://docs.intersystems.com)
Can we somehow comment this out for now? (Until we have more official documentation to point to more specifically?)

2024-11-12 18:04 UTC, isc-pbarton commented
I've made those two changes and put it back for your review

2024-11-13 14:26 UTC, isc-tleavitt approved these changes

2024-11-13 14:26 UTC, merged

2024-11-13 14:26 UTC, isc-tleavitt commented
Thank you @isc-pbarton! We'll probably get some more feedback from DP PM but merging as this is a great step forward.